language: php

php:
    # We only specify one version so we only get one worker
    - 5.4

env:
  - TEST_PHP_EXECUTABLE=php

notifications:
    email: false

before_script:
    - sudo iptables-save
    - sudo iptables -L
    - sudo iptables --append INPUT  --in-interface  lo --protocol all --jump ACCEPT
    - sudo iptables --append OUTPUT --out-interface lo --protocol all --jump ACCEPT
    - sudo iptables-save
    - sudo iptables -L

# Run PHPs run-tests.php 
script: 
  - php -f test.php
